name: Build - Windows
description: 'Build Windows release'

runs:
  using: "composite"
  steps:
    - name: Build miner
      run: dotnet publish tangram --configuration Release --self-contained -r win-x64 -p:PublishReadyToRun=true --output publish/tangram/${{ inputs.runtime }}
      shell: powershell

    - name: Package zip
      run: |
        Compress-Archive -Path publish/tangram/${{ inputs.runtime }} -DestinationPath ${{ github.workspace }}/tangram-xtgmnode_${{ env.VERSION }}.zip -Force
      shell: powershell